-- Esquema do AgendaSUS, reconstruído a partir das consultas feitas pelo app.

-- ---------------------------------------------------------------------------
-- Tabelas
-- ---------------------------------------------------------------------------

create table public.unidade_saude (
    id        bigint generated by default as identity primary key,
    nome      text not null,
    endereco  text,
    telefone  text
);

create table public.profissional (
    id                bigint generated by default as identity primary key,
    nome              text not null,
    especialidade     text not null,
    unidade_saude_id  bigint references public.unidade_saude (id) on delete set null
);

create table public.paciente (
    id               bigint generated by default as identity primary key,
    auth_user_id     uuid unique references auth.users (id) on delete cascade,
    nome             text not null,
    nome_social      text,
    cpf              text not null unique check (cpf ~ '^\d{11}$'),
    email            text not null unique,
    genero           text,
    telefone         text,
    endereco         text,
    cartao_sus       text,
    data_nascimento  date,
    created_at       timestamptz not null default now()
);

-- data_hora é "timestamp" (sem fuso) de propósito: o app grava "AAAA-MM-DDTHH:MM:SS"
-- no horário local e lê de volta com new Date(), que interpreta como horário local.
create table public.consulta (
    id                bigint generated by default as identity primary key,
    paciente_id       bigint not null references public.paciente (id) on delete cascade,
    profissional_id   bigint references public.profissional (id) on delete set null,
    unidade_saude_id  bigint references public.unidade_saude (id) on delete set null,
    status            text not null default 'agendada'
                      check (status in ('agendada', 'confirmada', 'realizada', 'cancelada', 'faltou')),
    data_hora         timestamp not null,
    especialidade     text,
    created_at        timestamptz not null default now()
);

create index consulta_paciente_idx on public.consulta (paciente_id, data_hora);

-- Impede dois agendamentos ativos no mesmo horário da mesma unidade.
create unique index consulta_horario_unico_idx
    on public.consulta (unidade_saude_id, data_hora)
    where status <> 'cancelada';

create table public.medicamento (
    id       bigint generated by default as identity primary key,
    nome     text not null,
    dose_mg  numeric not null
);

create table public.disponibilidade (
    id                    bigint generated by default as identity primary key,
    id_medicamento        bigint not null references public.medicamento (id) on delete cascade,
    id_unidade_saude      bigint not null references public.unidade_saude (id) on delete cascade,
    unidades_disponiveis  integer not null default 0 check (unidades_disponiveis >= 0),
    unique (id_medicamento, id_unidade_saude)
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.unidade_saude   enable row level security;
alter table public.profissional    enable row level security;
alter table public.paciente        enable row level security;
alter table public.consulta        enable row level security;
alter table public.medicamento     enable row level security;
alter table public.disponibilidade enable row level security;

-- Catálogos públicos (somente leitura).
create policy "leitura publica" on public.unidade_saude   for select to anon, authenticated using (true);
create policy "leitura publica" on public.profissional    for select to anon, authenticated using (true);
create policy "leitura publica" on public.medicamento     for select to anon, authenticated using (true);
create policy "leitura publica" on public.disponibilidade for select to anon, authenticated using (true);

-- Paciente só enxerga e edita o próprio registro. A criação é feita pela
-- Edge Function register-paciente com a service role.
create policy "paciente le o proprio registro" on public.paciente
    for select to authenticated
    using (auth_user_id = (select auth.uid()));

create policy "paciente atualiza o proprio registro" on public.paciente
    for update to authenticated
    using (auth_user_id = (select auth.uid()))
    with check (auth_user_id = (select auth.uid()));

-- Consultas: cada paciente só acessa as próprias.
create or replace function public.meu_paciente_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
    select id from public.paciente where auth_user_id = auth.uid();
$$;

create policy "paciente le as proprias consultas" on public.consulta
    for select to authenticated
    using (paciente_id = public.meu_paciente_id());

create policy "paciente agenda para si" on public.consulta
    for insert to authenticated
    with check (paciente_id = public.meu_paciente_id());

create policy "paciente altera as proprias consultas" on public.consulta
    for update to authenticated
    using (paciente_id = public.meu_paciente_id())
    with check (paciente_id = public.meu_paciente_id());

-- Horários ocupados de uma unidade num dia, sem expor de quem são as consultas.
create or replace function public.horarios_ocupados(p_data date, p_unidade_id bigint)
returns setof timestamp
language sql
stable
security definer
set search_path = ''
as $$
    select data_hora
    from public.consulta
    where unidade_saude_id = p_unidade_id
      and status <> 'cancelada'
      and data_hora >= p_data
      and data_hora <  p_data + 1;
$$;

revoke execute on function public.horarios_ocupados(date, bigint) from public, anon;
grant  execute on function public.horarios_ocupados(date, bigint) to authenticated;
revoke execute on function public.meu_paciente_id() from public, anon;
grant  execute on function public.meu_paciente_id() to authenticated;
