-- US-06: servidor da unidade autenticado com perfil de acesso.
-- Documentação: docs/portal-da-unidade.md e docs/politicas-de-acesso.md
--
-- Três camadas:
--   1. Hook de autenticação: servidor sem vínculo ativo não recebe token (login recusado
--      por qualquer caminho, inclusive chamando a API do Supabase direto). Também vale
--      na renovação do token, então desativar um servidor derruba a sessão dele.
--   2. Portal só por funções (portal_*): cada uma confere, a cada chamada, que quem chama
--      é servidor com vínculo ativo, e devolve só dados da unidade dele.
--   3. Sem privilégio direto: servidor não lê as tabelas paciente/consulta/servidor.

-- ---------------------------------------------------------------------------
-- 1. Servidores
-- ---------------------------------------------------------------------------

create table public.servidor (
    id                bigint generated by default as identity primary key,
    auth_user_id      uuid not null unique references auth.users (id) on delete cascade,
    unidade_saude_id  bigint not null references public.unidade_saude (id),
    nome              text not null,
    email             text not null unique,
    matricula         text not null unique,
    perfil            text not null check (perfil in ('atendente', 'gestor')),
    ativo             boolean not null default true,
    created_at        timestamptz not null default now()
);

alter table public.servidor enable row level security;
-- Sem políticas e sem GRANT para anon/authenticated: ninguém do app lê a tabela direto.
-- O acesso é só pelas funções portal_* abaixo. Cadastro pela service_role.

comment on table public.servidor is
    'Servidores das unidades (portal). RLS ativo sem políticas e sem GRANT para '
    'anon/authenticated: acesso só pelas funções portal_*, que exigem vínculo ativo. '
    'Cadastro e desativação pela service_role.';
comment on column public.servidor.perfil is
    'atendente: opera a agenda da unidade. gestor: opera a agenda e vê a equipe da unidade.';
comment on column public.servidor.ativo is
    'Vínculo ativo com a unidade. false = login recusado (hook) e portal negado.';

-- ---------------------------------------------------------------------------
-- 2. Checagem central: quem chama é servidor ativo (e com o perfil exigido)?
-- ---------------------------------------------------------------------------

create function public.exigir_servidor(p_perfis text[] default null)
returns public.servidor
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v public.servidor;
begin
    select * into v
    from public.servidor s
    where s.auth_user_id = auth.uid() and s.ativo;

    if v.id is null then
        raise exception 'Acesso restrito a servidores com vínculo ativo.'
            using errcode = '42501';
    end if;
    if p_perfis is not null and not v.perfil = any (p_perfis) then
        raise exception 'Seu perfil (%) não tem acesso a esta função.', v.perfil
            using errcode = '42501';
    end if;
    return v;
end;
$$;

revoke execute on function public.exigir_servidor(text[]) from public, anon, authenticated;

comment on function public.exigir_servidor(text[]) is
    'Uso interno das funções portal_*. Devolve o servidor ativo do usuário logado ou '
    'lança 42501. Não é executável pelo app.';

-- ---------------------------------------------------------------------------
-- 3. Funções do portal
-- ---------------------------------------------------------------------------

create function public.portal_meu_perfil()
returns table (
    nome text, email text, matricula text, perfil text,
    unidade_id bigint, unidade_nome text, unidade_fuso text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v public.servidor := public.exigir_servidor();
begin
    return query
    select v.nome, v.email, v.matricula, v.perfil, u.id, u.nome, u.fuso_horario
    from public.unidade_saude u
    where u.id = v.unidade_saude_id;
end;
$$;

create function public.portal_agenda(p_data date)
returns table (
    consulta_id bigint, data_hora timestamptz, status text, especialidade text,
    paciente_nome text, paciente_cpf text, paciente_telefone text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v public.servidor := public.exigir_servidor();
begin
    return query
    select c.id, c.data_hora, c.status, c.especialidade,
           coalesce(nullif(p.nome_social, ''), p.nome),
           -- CPF mascarado: o suficiente para conferir com o documento no balcão.
           '***.' || substr(p.cpf, 4, 3) || '.' || substr(p.cpf, 7, 3) || '-**',
           p.telefone
    from public.consulta c
    join public.paciente p on p.id = c.paciente_id
    join public.unidade_saude u on u.id = c.unidade_saude_id
    where c.unidade_saude_id = v.unidade_saude_id
      and c.data_hora >= (p_data::timestamp       at time zone u.fuso_horario)
      and c.data_hora <  ((p_data + 1)::timestamp at time zone u.fuso_horario)
    order by c.data_hora;
end;
$$;

create function public.portal_atualizar_status(p_consulta_id bigint, p_status text)
returns table (consulta_id bigint, status text)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
    v public.servidor := public.exigir_servidor();
    v_atual text;
begin
    if p_status not in ('confirmada', 'realizada', 'faltou', 'cancelada') then
        raise exception 'Status inválido: %.', p_status using errcode = '22023';
    end if;

    -- Consulta de outra unidade é tratada como inexistente (não revela que existe).
    select c.status into v_atual
    from public.consulta c
    where c.id = p_consulta_id and c.unidade_saude_id = v.unidade_saude_id
    for update;

    if v_atual is null then
        raise exception 'Consulta não encontrada nesta unidade.' using errcode = 'P0002';
    end if;
    if v_atual not in ('agendada', 'confirmada') then
        raise exception 'Consulta já está %; não pode ser alterada.', v_atual using errcode = '22023';
    end if;

    return query
    update public.consulta c set status = p_status
    where c.id = p_consulta_id
    returning c.id, c.status;
end;
$$;

create function public.portal_equipe()
returns table (nome text, email text, matricula text, perfil text, ativo boolean)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v public.servidor := public.exigir_servidor(array['gestor']);
begin
    return query
    select s.nome, s.email, s.matricula, s.perfil, s.ativo
    from public.servidor s
    where s.unidade_saude_id = v.unidade_saude_id
    order by s.ativo desc, s.nome;
end;
$$;

revoke execute on function public.portal_meu_perfil()                    from public, anon;
revoke execute on function public.portal_agenda(date)                    from public, anon;
revoke execute on function public.portal_atualizar_status(bigint, text)  from public, anon;
revoke execute on function public.portal_equipe()                        from public, anon;
grant  execute on function public.portal_meu_perfil()                    to authenticated;
grant  execute on function public.portal_agenda(date)                    to authenticated;
grant  execute on function public.portal_atualizar_status(bigint, text)  to authenticated;
grant  execute on function public.portal_equipe()                        to authenticated;

comment on function public.portal_meu_perfil() is
    'Portal: dados do servidor logado e da unidade dele. Paciente ou servidor inativo: 42501.';
comment on function public.portal_agenda(date) is
    'Portal: consultas da unidade do servidor no dia (dia no fuso da unidade), com nome, '
    'CPF mascarado e telefone do paciente. Nunca devolve outra unidade.';
comment on function public.portal_atualizar_status(bigint, text) is
    'Portal: muda o status (confirmada/realizada/faltou/cancelada) de consulta ativa da '
    'unidade do servidor. Consulta de outra unidade: "não encontrada".';
comment on function public.portal_equipe() is
    'Portal: servidores da unidade. Só perfil gestor.';

-- ---------------------------------------------------------------------------
-- 4. Hook de autenticação: recusa token para servidor sem vínculo ativo
--    Ativado em supabase/config.toml ([auth.hook.custom_access_token]); no Supabase
--    hospedado, em Authentication > Hooks.
-- ---------------------------------------------------------------------------

create function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_ativo boolean;
begin
    select s.ativo into v_ativo
    from public.servidor s
    where s.auth_user_id = (event ->> 'user_id')::uuid;

    if v_ativo is false then
        return jsonb_build_object('error', jsonb_build_object(
            'http_code', 403,
            'message', 'Servidor sem vínculo ativo com uma unidade. Procure a coordenação.'
        ));
    end if;

    return event;  -- paciente e servidor ativo: token segue sem alteração
end;
$$;

grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook(jsonb) to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook(jsonb) from public, anon, authenticated;

comment on function public.custom_access_token_hook(jsonb) is
    'Hook do Supabase Auth: impede emissão de token (login e renovação) para servidor '
    'com ativo = false. Executado só por supabase_auth_admin.';
