-- Esquema base do AgendaSUS.
--
-- Esta migration foi ajustada para dois cenarios:
-- 1. banco novo: cria as tabelas, policies e funcoes base;
-- 2. banco da equipe ja existente: preserva dados/colunas atuais e adiciona apenas
--    o que estiver faltando para as proximas migrations funcionarem.
--
-- Observacao: fuso_horario nao e criado aqui de proposito. Ele pertence a migration
-- 20260930180000_data_hora_com_fuso.sql.

-- ---------------------------------------------------------------------------
-- Tabelas
-- ---------------------------------------------------------------------------

create table if not exists public.unidade_saude (
    id        bigint generated by default as identity primary key,
    cnes      text,
    nome      text not null,
    endereco  text,
    telefone  text
);

alter table public.unidade_saude
    add column if not exists cnes text,
    add column if not exists nome text,
    add column if not exists endereco text,
    add column if not exists telefone text;

create table if not exists public.profissional (
    id                bigint generated by default as identity primary key,
    nome              text not null,
    cpf               text,
    registro_conselho text,
    especialidade     text,
    unidade_saude_id  bigint references public.unidade_saude (id) on delete set null
);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'profissional'
          and column_name = 'unidade_id'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'profissional'
          and column_name = 'unidade_saude_id'
    ) then
        alter table public.profissional rename column unidade_id to unidade_saude_id;
    elsif exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'profissional'
          and column_name = 'unidade_id'
    ) and exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'profissional'
          and column_name = 'unidade_saude_id'
    ) then
        update public.profissional
        set unidade_saude_id = coalesce(unidade_saude_id, unidade_id)
        where unidade_saude_id is null;
    end if;
end;
$$;

alter table public.profissional
    add column if not exists cpf text,
    add column if not exists registro_conselho text,
    add column if not exists especialidade text,
    add column if not exists unidade_saude_id bigint;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.profissional'::regclass
          and contype = 'f'
          and conkey = array[
              (select attnum
               from pg_attribute
               where attrelid = 'public.profissional'::regclass
                 and attname = 'unidade_saude_id')
          ]::smallint[]
    ) then
        alter table public.profissional
            add constraint profissional_unidade_saude_id_fkey
            foreign key (unidade_saude_id)
            references public.unidade_saude (id)
            on delete set null;
    end if;
end;
$$;

create table if not exists public.paciente (
    id               bigint generated by default as identity primary key,
    auth_user_id     uuid references auth.users (id) on delete cascade,
    nome             text not null,
    nome_social      text,
    cpf              text,
    email            text,
    genero           text,
    telefone         text,
    endereco         text,
    cartao_sus       text,
    data_nascimento  date,
    created_at       timestamptz not null default now()
);

alter table public.paciente
    add column if not exists auth_user_id uuid,
    add column if not exists nome text,
    add column if not exists nome_social text,
    add column if not exists cpf text,
    add column if not exists email text,
    add column if not exists genero text,
    add column if not exists telefone text,
    add column if not exists endereco text,
    add column if not exists cartao_sus text,
    add column if not exists data_nascimento date,
    add column if not exists created_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.paciente'::regclass
          and contype = 'f'
          and conkey = array[
              (select attnum
               from pg_attribute
               where attrelid = 'public.paciente'::regclass
                 and attname = 'auth_user_id')
          ]::smallint[]
    ) then
        alter table public.paciente
            add constraint paciente_auth_user_id_fkey
            foreign key (auth_user_id)
            references auth.users (id)
            on delete cascade;
    end if;
end;
$$;

create unique index if not exists paciente_cpf_unique_idx
    on public.paciente (cpf)
    where cpf is not null;

create unique index if not exists paciente_email_unique_idx
    on public.paciente (email)
    where email is not null;

do $$
begin
    if not exists (
        select auth_user_id
        from public.paciente
        where auth_user_id is not null
        group by auth_user_id
        having count(*) > 1
    ) then
        create unique index if not exists paciente_auth_user_id_unique_idx
            on public.paciente (auth_user_id)
            where auth_user_id is not null;
    else
        raise notice 'Nao foi criado indice unico em paciente.auth_user_id: existem valores duplicados.';
    end if;
end;
$$;

create table if not exists public.consulta (
    id                bigint generated by default as identity primary key,
    paciente_id       bigint not null references public.paciente (id) on delete cascade,
    profissional_id   bigint references public.profissional (id) on delete set null,
    unidade_saude_id  bigint references public.unidade_saude (id) on delete set null,
    status            text default 'agendada',
    data_hora         timestamp,
    especialidade     text,
    created_at        timestamptz not null default now()
);

alter table public.consulta
    add column if not exists paciente_id bigint,
    add column if not exists profissional_id bigint,
    add column if not exists unidade_saude_id bigint,
    add column if not exists status text,
    add column if not exists data_hora timestamp,
    add column if not exists especialidade text,
    add column if not exists created_at timestamptz not null default now();

update public.consulta
set status = 'agendada'
where status is null;

alter table public.consulta
    alter column status set default 'agendada',
    alter column status set not null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'consulta_status_check'
          and conrelid = 'public.consulta'::regclass
    ) then
        alter table public.consulta
            add constraint consulta_status_check
            check (status in ('agendada', 'confirmada', 'realizada', 'cancelada', 'faltou'))
            not valid;
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from public.consulta
        where data_hora is null
    ) then
        alter table public.consulta alter column data_hora set not null;
    else
        raise notice 'consulta.data_hora permanece nullable: existem registros sem data_hora.';
    end if;
end;
$$;

create index if not exists consulta_paciente_idx
    on public.consulta (paciente_id, data_hora);

do $$
begin
    if not exists (
        select 1
        from pg_indexes
        where schemaname = 'public'
          and indexname = 'consulta_horario_unico_idx'
    ) and not exists (
        select unidade_saude_id, data_hora
        from public.consulta
        where status <> 'cancelada'
          and unidade_saude_id is not null
          and data_hora is not null
        group by unidade_saude_id, data_hora
        having count(*) > 1
    ) then
        create unique index consulta_horario_unico_idx
            on public.consulta (unidade_saude_id, data_hora)
            where status <> 'cancelada';
    elsif not exists (
        select 1
        from pg_indexes
        where schemaname = 'public'
          and indexname = 'consulta_horario_unico_idx'
    ) then
        raise notice 'Nao foi criado consulta_horario_unico_idx: existem consultas ativas duplicadas no mesmo horario/unidade.';
    end if;
end;
$$;

create table if not exists public.medicamento (
    id       bigint generated by default as identity primary key,
    nome     text not null,
    dose_mg  numeric
);

alter table public.medicamento
    add column if not exists nome text,
    add column if not exists dose_mg numeric;

create table if not exists public.disponibilidade (
    id_medicamento        bigint not null references public.medicamento (id) on delete cascade,
    id_unidade            bigint not null references public.unidade_saude (id) on delete cascade,
    unidades_disponiveis  integer not null default 0 check (unidades_disponiveis >= 0),
    primary key (id_medicamento, id_unidade)
);

alter table public.disponibilidade
    add column if not exists id_medicamento bigint,
    add column if not exists id_unidade bigint,
    add column if not exists unidades_disponiveis integer not null default 0;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.unidade_saude   enable row level security;
alter table public.profissional    enable row level security;
alter table public.paciente        enable row level security;
alter table public.consulta        enable row level security;
alter table public.medicamento     enable row level security;
alter table public.disponibilidade enable row level security;

drop policy if exists "leitura publica" on public.unidade_saude;
drop policy if exists "leitura publica" on public.profissional;
drop policy if exists "leitura publica" on public.medicamento;
drop policy if exists "leitura publica" on public.disponibilidade;

create policy "leitura publica" on public.unidade_saude   for select to anon, authenticated using (true);
create policy "leitura publica" on public.profissional    for select to anon, authenticated using (true);
create policy "leitura publica" on public.medicamento     for select to anon, authenticated using (true);
create policy "leitura publica" on public.disponibilidade for select to anon, authenticated using (true);

drop policy if exists "paciente le o proprio registro" on public.paciente;
drop policy if exists "paciente atualiza o proprio registro" on public.paciente;

create policy "paciente le o proprio registro" on public.paciente
    for select to authenticated
    using (auth_user_id = (select auth.uid()));

create policy "paciente atualiza o proprio registro" on public.paciente
    for update to authenticated
    using (auth_user_id = (select auth.uid()))
    with check (auth_user_id = (select auth.uid()));

create or replace function public.meu_paciente_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
    select id from public.paciente where auth_user_id = auth.uid();
$$;

drop policy if exists "paciente le as proprias consultas" on public.consulta;
drop policy if exists "paciente agenda para si" on public.consulta;
drop policy if exists "paciente altera as proprias consultas" on public.consulta;

create policy "paciente le as proprias consultas" on public.consulta
    for select to authenticated
    using (paciente_id = public.meu_paciente_id());

create policy "paciente agenda para si" on public.consulta
    for insert to authenticated
    with check (paciente_id = public.meu_paciente_id());

create policy "paciente altera as proprias consultas" on public.consulta
    for update to authenticated
    using (paciente_id = public.meu_paciente_id())
    with check (paciente_id = public.meu_paciente_id());

create or replace function public.horarios_ocupados(p_data date, p_unidade_id bigint)
returns setof timestamp
language sql
stable
security definer
set search_path = ''
as $$
    select data_hora
    from public.consulta
    where unidade_saude_id = p_unidade_id
      and status <> 'cancelada'
      and data_hora >= p_data
      and data_hora <  p_data + 1;
$$;

revoke execute on function public.horarios_ocupados(date, bigint) from public, anon;
grant  execute on function public.horarios_ocupados(date, bigint) to authenticated;
revoke execute on function public.meu_paciente_id() from public, anon;
grant  execute on function public.meu_paciente_id() to authenticated;
