-- US-01 - Grade de atendimento por profissional e RPC de disponibilidade
-- Copie e cole este arquivo no SQL Editor do Supabase.

create table if not exists public.grade_atendimento (
    id bigint generated by default as identity primary key,
    unidade_saude_id bigint not null references public.unidade_saude(id) on delete cascade,
    profissional_id bigint not null references public.profissional(id) on delete cascade,
    dia_semana smallint not null check (dia_semana between 0 and 6),
    hora_inicio time not null,
    hora_fim time not null,
    intervalo_minutos integer not null default 30 check (intervalo_minutos > 0),
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (hora_fim > hora_inicio)
);

comment on table public.grade_atendimento is
    'Grade de horarios de atendimento por unidade e profissional. dia_semana usa 0=domingo e 6=sabado.';

create index if not exists idx_grade_atendimento_lookup
    on public.grade_atendimento (unidade_saude_id, profissional_id, dia_semana, ativo);

create or replace function public.set_grade_atendimento_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_grade_atendimento_updated_at on public.grade_atendimento;
create trigger trg_grade_atendimento_updated_at
before update on public.grade_atendimento
for each row
execute function public.set_grade_atendimento_updated_at();

create or replace function public.validar_grade_atendimento_profissional()
returns trigger
language plpgsql
as $$
begin
    if not exists (
        select 1
        from public.profissional p
        where p.id = new.profissional_id
          and p.unidade_saude_id = new.unidade_saude_id
    ) then
        raise exception 'O profissional informado nao pertence a unidade informada.';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_validar_grade_atendimento_profissional on public.grade_atendimento;
create trigger trg_validar_grade_atendimento_profissional
before insert or update on public.grade_atendimento
for each row
execute function public.validar_grade_atendimento_profissional();

alter table public.grade_atendimento enable row level security;

drop policy if exists grade_atendimento_select on public.grade_atendimento;
create policy grade_atendimento_select
on public.grade_atendimento
for select
using (true);

grant select on public.grade_atendimento to anon, authenticated;

create or replace function public.buscar_disponibilidade_agenda(
    p_unidade_id bigint,
    p_profissional_id bigint,
    p_data date
)
returns table(horario text)
language sql
stable
security definer
set search_path = public
as $$
    with profissional_valido as (
        select p.id
        from public.profissional p
        where p.id = p_profissional_id
          and p.unidade_saude_id = p_unidade_id
    ),
    slots as (
        select
            slot.data_hora as data_hora_local,
            slot.data_hora at time zone u.fuso_horario as data_hora
        from public.grade_atendimento g
        join profissional_valido pv on pv.id = g.profissional_id
        join public.unidade_saude u on u.id = g.unidade_saude_id
        cross join lateral generate_series(
            p_data + g.hora_inicio,
            (p_data + g.hora_fim) - make_interval(mins => g.intervalo_minutos),
            make_interval(mins => g.intervalo_minutos)
        ) as slot(data_hora)
        where g.unidade_saude_id = p_unidade_id
          and g.profissional_id = p_profissional_id
          and g.dia_semana = extract(dow from p_data)::smallint
          and g.ativo = true
    ),
    ocupados as (
        select c.data_hora
        from public.consulta c
        join public.unidade_saude u on u.id = c.unidade_saude_id
        where c.unidade_saude_id = p_unidade_id
          and c.profissional_id = p_profissional_id
          and c.data_hora >= (p_data::timestamp at time zone u.fuso_horario)
          and c.data_hora < ((p_data + 1)::timestamp at time zone u.fuso_horario)
          and lower(coalesce(c.status, '')) <> 'cancelada'
    )
    select distinct to_char(s.data_hora_local, 'HH24:MI') as horario
    from slots s
    where s.data_hora > now()
      and not exists (
          select 1
          from ocupados o
          where o.data_hora = s.data_hora
      )
    order by horario;
$$;

grant execute on function public.buscar_disponibilidade_agenda(bigint, bigint, date) to anon, authenticated;

-- Exemplo opcional para cadastrar grade:
-- insert into public.grade_atendimento
--     (unidade_saude_id, profissional_id, dia_semana, hora_inicio, hora_fim, intervalo_minutos, ativo)
-- values
--     (1, 1, 1, '08:00', '12:00', 30, true),
--     (1, 1, 1, '13:00', '17:00', 30, true);
